export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const ADD_PRODUCTS_REQUEST = 'ADD_PRODUCTS_REQUEST';
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS_SUCCESS';
export const ADD_PRODUCTS_FAIL = 'ADD_PRODUCTS_FAIL';

export const EDIT_PRODUCTS_REQUEST = 'EDIT_PRODUCTS_REQUEST';
export const EDIT_PRODUCTS_SUCCESS = 'EDIT_PRODUCTS_SUCCESS';
export const EDIT_PRODUCTS_FAIL = 'EDIT_PRODUCTS_FAIL';